#!/bin/sh

LIBJPEG12_SO=libjpeg.so
OUT_FILE=rename_symbols_12.h

if objdump -t $LIBJPEG12_SO | grep jpeg_start_decompress_12> /dev/null; then
    echo "libjpeg must be rebuilt first with DSUFFIX_LIBJPEG12_SYMBOLS=0";
    exit 1
fi

echo "/* This section has been generated by rename_symbols_12.sh. *DO NOT EDIT MANUALLY !* */" > $OUT_FILE

symbol_list=$(objdump -t $LIBJPEG12_SO  | grep .text | awk '{print $6}' | grep -v -e .text -e __do_global -e __bss_start -e _edata -e _end -e _fini -e _init -e register_tm_clones -e constprop. -e .cold -e .part -e .isra | sort)
for symbol in $symbol_list
do
    echo "#define $symbol ${symbol}_12" >> $OUT_FILE
done

rodata_symbol_list=$(objdump -t $LIBJPEG12_SO  | grep "\\.rodata" |  awk '{print $6}' | grep -v "\\.")
for symbol in $rodata_symbol_list
do
    echo "#define $symbol ${symbol}_12" >> $OUT_FILE
done

data_symbol_list=$(objdump -t $LIBJPEG12_SO  | grep "\\.data"  | grep -v -e __dso_handle -e __TMC_END__ | awk '{print $6}' | grep -v "\\.")
for symbol in $data_symbol_list
do
    echo "#define $symbol ${symbol}_12" >> $OUT_FILE
done

bss_symbol_list=$(objdump -t $LIBJPEG12_SO  | grep "\\.bss" |  awk '{print $6}' | grep -v "\\.")
for symbol in $bss_symbol_list
do
    echo "#define $symbol ${symbol}_12" >> $OUT_FILE
done

echo "/* End of section generated by rename_symbols_12.sh. */" >> $OUT_FILE

echo "File rename_symbols_12.h has been generated. Its content must be pasted into jmorecfg.h"
